### ISSUE TITLE
Versions of language-filter above v3.0.1 don't work

### ISSUE THREAD

**Issue by P1ayer4312** [sanity-io/language-filter#47]
We recently updated Sanity and all the plugins to the latest versions. For the language filter only the dropdown menu is shown, but when I choose different languages nothing happens, only the language gets deselected from the dropdown menu and nothing else.

We previously had Sanity v3.7, now we have v3.14.1
For the language-filter any version above v3.0.1 does not work from our testing.

**Comment by SimeonGriggs** [comment]
Are you able to log the result of your `filterField` function to confirm it's intercepting fields as expected?

**Comment by pgrzyb** [comment]
It is not. Logging inside the function yields no results - sorry, I forgot to mention this on GitHub after saying it on Slack 🤦‍♂️ 
Not that it helps, but just for reference: https://sanity-io-land.slack.com/archives/C9Z7RC3V1/p1688368828527809

**Comment by SimeonGriggs** [comment]
Got it, are your internationalized object fields just inline objects? For example:

```ts
export const localeString = defineType({
  title: 'Localized string',
  name: 'localeString',
  type: 'object',
  fields: [ ...
```

Or have you registered it as a custom type? And use it like so:

```ts
    defineField({
      title: 'Localized string (OBJECT)',
      name: 'localeStringObject',
      type: 'localeString',
    }),
```

You may need to register it as a custom type in order to show and hide the fields.

**Comment by spacedawwwg** [comment]
@SimeonGriggs we have the same issue, and yes we're using internationalised object fields

**Comment by spacedawwwg** [comment]
```JS
  languageFilter({
    supportedLanguages: [
      ...languages.map(language => ({
        id: language.name,
        title: language.title,
      })),
    ],
    defaultLanguages: [languages[0].name],
    documentTypes: [],
    filterField: (_enclosingType, field, selectedLanguageIds) =>
      !languages.map(lang => lang.name).includes(field.name) ||
      selectedLanguageIds.includes(field.name),
  }),
```

**Comment by SimeonGriggs** [comment]
Using the same `filterField` function as yours (checking that the member name is not a language OR that it is a language and is currently selected), mine is still working in the latest version.

I can recreate the issue reported here, but can resolve it with the `filterField` function. 

<img width="644" alt="Screenshot 2023-07-18 at 14 33 00" src="https://github.com/sanity-io/language-filter/assets/9684022/09f38c1a-8355-4e88-87ff-fd1e3eac053d">

I'd like to recreate a version of the `filterField` that worked in a previous version and does not in this newer one. There should not have been a breaking change between versions here for this logic.

**Comment by spacedawwwg** [comment]
@SimeonGriggs I cant even get `filterField` to log out anything

```TS
languageFilter({
    supportedLanguages: [
      ...languages.map(language => ({
        id: language.name,
        title: language.title,
      })),
    ],
    defaultLanguages: [languages[0].name],
    documentTypes: [],
    filterField: (_enclosingType, field, selectedLanguageIds) =>
    
      // THIS NEVER FIRES
      console.log(selectedLanguageIds)
      
      !languages.map(lang => lang.name).includes(field.name) ||
      selectedLanguageIds.includes(field.name),
  }),
```

Am I missing something obvious that has changed?

**Comment by spacedawwwg** [comment]
![ezgif-5-6415ff35b1](https://github.com/sanity-io/language-filter/assets/1691867/2e3b29cf-6a9b-45e1-9751-edc97b839e1b)

**Comment by SimeonGriggs** [comment]
@spacedawwwg Still working on recreating the issue with your code examples...

1. Your `documentTypes` array is empty in this snippet?
2. The object example uses field names `en` and `fr` but your languages array has locale/market pairs like `en_GB` and `ar_SA` – can you confirm your field **names** share the same values as your language **ID's**?

**Comment by spacedawwwg** [comment]
@SimeonGriggs 

1. `documentTypes` was an empty array actually, it can be removed as we moved to use the `options` to enable it for specific schemas instead as this must have just been left by mistake.
2. no, my example above using `en`, `fr` was just pseudo code - our real languages use the `en_GB` and `ar_SA` pattern. All languages are modelled like this:

```TS
export const languages: Languages = [
  {
    name: 'en_GB',
    code: 'en-GB',
    title: 'English',
    direction: 'ltr',
  },
  {
    name: 'ar_SA',
    code: 'ar-SA',
    title: 'Arabic',
    direction: 'rtl',
  },
  // etc.
  ...
]

**Comment by SimeonGriggs** [comment]
That's it!

Objects in document types where the configuration was on the schema – and not in the plugin config – weren't being run through the custom object input.
